dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - build and publish
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      addons:
        mariadb: '10.2'
      install: skip
      before_script:
        - mysql -uroot < databases/create_databases.sql
        - ./gradlew testMigrate
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "applications/board-server/build/libs/board-server.jar"
          - "applications/trusted-review-server/build/libs/trusted-review-server.jar"
          - "applications/board-review-server/build/libs/board-review-server.jar"
        skip_cleanup: true